version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: aigc_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/aigc_platform
      - REDIS_URL=redis://redis:6379
      - VOLC_ACCESS_KEY=${VOLC_ACCESS_KEY}
      - VOLC_SECRET_KEY=${VOLC_SECRET_KEY}
      - VOLC_REGION=${VOLC_REGION:-cn-north-1}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-change-in-production}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  celery:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/aigc_platform
      - REDIS_URL=redis://redis:6379
      - VOLC_ACCESS_KEY=${VOLC_ACCESS_KEY}
      - VOLC_SECRET_KEY=${VOLC_SECRET_KEY}
      - VOLC_REGION=${VOLC_REGION:-cn-north-1}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python -m celery -A tasks.celery worker --loglevel=info

# 删除或注释掉 volumes 部分
# volumes:
#   postgres_data: ./data/postgres
#   redis_data: ./data/redis